# Usar una imagen oficial de Java
FROM openjdk:17-jdk-slim

# Crear un directorio para la aplicación
WORKDIR /app

# Copiar el archivo JAR generado por Spring Boot
COPY target/*.jar app.jar

# Exponer el puerto que utilizará la aplicación
EXPOSE 8080

# Ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
